import { Montserrat } from "next/font/google";
import "./global.css";
import Footer from "@/components/footer/Footer";

import Hero from "@/components/hero/page";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Tyson Nguyen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  flex flex-col justify-center items-center bg-pattern bg-no-repeat bg-center bg-cover overflow-x-hidden`}
      >
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}
